/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

import { Chapter } from '../types';

/**
 * This file centralizes the canonical chapter lists for all novels in the
 * Jason Z. Christie shared universe.
 */

export const everythingWentBlackChapters: Chapter[] = [
    { title: 'Tokio Motherfucking Jones', summary: 'Introduction to Tokio Jones, his philosophy, and his formative years in Houston\'s Fifth Ward.', characters: ['Tokio Jones'] },
    { title: 'Cuz', summary: 'Tokio\'s cousin Tracy arrives and introduces him to the harsh realities of the pimp game by turning his girlfriend, Janet.', characters: ['Tokio Jones', 'Tracy', 'Janet'] },
    { title: 'Rebranded', summary: 'Disillusioned with pimping, Tokio decides to learn a trade and enrolls in welding classes, finding a new path.', characters: ['Tokio Jones'] },
    { title: 'Everybody’s Workin’ For The Weekend', summary: 'Tokio meets George, a maintenance man who becomes his first legitimate mentor and gives him his first major job.', characters: ['Tokio Jones', 'George'] },
    { title: 'Hard-Ass, Pipe-Hittin’ Nigga', summary: 'Tokio proves his skills and work ethic to George, earning his trust and an apprenticeship for the summer.', characters: ['Tokio Jones', 'George'] },
    { title: 'Summer Lovin’', summary: 'Tokio gains more experience as a tradesman and has a formative romantic encounter with an older woman in the building, Yolanda.', characters: ['Tokio Jones', 'Yolanda'] },
    { title: 'Clack Clack', summary: 'Tracy is murdered, and as a result, Tokio\'s mother decides to send him to Los Angeles to escape the escalating violence of Houston.', characters: ['Tokio Jones', 'Janet'] },
    { title: 'The Jackson Family', summary: 'Tokio arrives in L.A. and meets his Great-Aunt Tilly and his brilliant, precocious young cousin, Maxine "Maxxy" Jackson.', characters: ['Tokio Jones', 'Aunt Tilly', 'Maxine "Maxxy" Jackson'] },
    { title: 'Welcome to the Jungle', summary: 'Maxxy gives Tokio a tour of their neighborhood, revealing the complex and dangerous gang territories of Lynwood.', characters: ['Tokio Jones', 'Maxine "Maxxy" Jackson'] },
    { title: 'Dead Poets Society', summary: 'Tokio accompanies Maxxy to her monthly library meeting, where he is introduced to a new world of literature and intellectualism.', characters: ['Tokio Jones', 'Maxine "Maxxy" Jackson', 'Aunt Tilly', 'Sarah'] },
    { title: 'Watt’s Up', summary: 'A family dinner turns into a discussion about the history of Watts, race, and economics, deepening Tokio\'s education.', characters: ['Tokio Jones', 'Maxine "Maxxy" Jackson', 'Aunt Tilly'] },
    { title: 'Bullet Points', summary: 'A drive-by shooting targets their house, and Tokio is shocked by Aunt Tilly and Maxxy\'s calm, prepared, and lethal response.', characters: ['Tokio Jones', 'Maxine "Maxxy" Jackson', 'Aunt Tilly'] },
    { title: 'Honeybear', summary: 'Tokio begins his new life in L.A., starting a job as a mechanic and processing the recent violence and changes in his life.', characters: ['Tokio Jones', 'Aunt Tilly', 'Cooter'] },
    { title: 'Just A Good Ole’ Boy', summary: 'Tokio settles into his mechanic job, learns to drive, and continues his personal growth under the guidance of Aunt Tilly.', characters: ['Tokio Jones', 'Aunt Tilly', 'Cooter'] },
    { title: 'Hue-Colored Glasses', summary: 'Through church, Tokio meets and falls for Hue Nguyen, beginning his first serious, romantic relationship.', characters: ['Tokio Jones', 'Aunt Tilly', 'Maxine "Maxxy" Jackson', 'Hue Nguyen'] },
    { title: 'Babygirl', summary: 'Tokio gets his driver\'s license and, with Aunt Til\'s help, buys his dream car, a \'63 Impala lowrider, a symbol of his new life and status.', characters: ['Tokio Jones', 'Aunt Tilly'] },
    { title: 'When in Spain', summary: 'Tokio takes Hue on their first official date, a fancy dinner and a movie, navigating the complexities of her family and their cultural differences.', characters: ['Tokio Jones', 'Hue Nguyen', 'Aunt Tilly'] },
    { title: 'Inscrutable', summary: 'Hue goes away to college, and Tokio learns he must return to Houston, forcing their separation.', characters: ['Tokio Jones', 'Hue Nguyen', 'Aunt Tilly', 'Maxine "Maxxy" Jackson'] },
    { title: 'What The Pho', summary: 'At Hue\'s going-away dinner, Tokio learns his time in L.A. is over as his mother has arranged for his return to Texas.', characters: ['Tokio Jones', 'Hue Nguyen', 'Aunt Tilly', 'Maxine "Maxxy" Jackson'] },
    { title: 'Such Sweet Sorrow', summary: 'Tokio spends his last few days in L.A. with Til and Maxxy, who throw him a heartfelt going-away party.', characters: ['Tokio Jones', 'Aunt Tilly', 'Maxine "Maxxy" Jackson'] },
    { title: 'Welcome Home', summary: 'Tokio drives his new car from L.A. to Houston, a journey of self-reflection that ends in a violent confrontation in his old neighborhood.', characters: ['Tokio Jones'] },
    { title: 'Up for the Downstroke', summary: 'Tokio settles into his new home in Channelview, reflects on Aunt Til\'s secret life, gets his car repaired, and re-establishes contact with George and Yolanda.', characters: ['Tokio Jones', 'Yolanda', 'George'] },
    { title: 'Working Man', summary: 'Tokio starts a new, high-paying construction job as a welder and labor foreman, beginning the next phase of his legitimate career.', characters: ['Tokio Jones', 'Ward'] },
    { title: 'Grumblings from a Grumpy Old Construction Worker', summary: 'Tokio reflects on his years in construction, his relationship with Morgan, and the slow, inevitable pull back towards The Life.', characters: ['Tokio Jones', 'Morgan'] },
    { title: 'Pimpin’ Ain’t Easy', summary: 'Tokio and Morgan begin to roleplay pimp/prostitute scenarios, which quickly escalates into Morgan actually turning her first trick.', characters: ['Tokio Jones', 'Morgan'] },
    { title: '99 Problems', summary: 'Tokio and Morgan navigate the difficult realities of The Life, including violence from a john, arrests, and disease.', characters: ['Tokio Jones', 'Morgan'] },
    { title: 'Baby Boss', summary: 'Morgan brings home a new girl, Angela, to join their stable, changing the dynamic of their relationship and business.', characters: ['Tokio Jones', 'Morgan', 'Angela'] },
    { title: 'Pimp Shit', summary: 'The trio travels to Las Vegas for the Player\'s Ball, where Tokio hopes to establish himself as a legitimate player.', characters: ['Tokio Jones', 'Morgan', 'Angela'] },
    { title: 'The Great Reset', summary: 'The first night in Vegas, a visit to the AVN awards and a private afterparty with Curtis Mayfield, opens Tokio\'s eyes to the "Ultimate Hustle."', characters: ['Tokio Jones', 'Morgan', 'Angela', 'Curtis Mayfield'] },
    { title: 'Suited', summary: 'Tokio prepares for the Player\'s Ball by having a custom, Asian-inspired suit made by a master tailor in North Las Vegas.', characters: ['Tokio Jones', 'Morgan', 'Angela'] },
    { title: 'Grand Entrance', summary: 'Tokio and his girls make a grand entrance at the Player\'s Ball, witnessing the spectacle of the pimping world and an appearance by Isaac Hayes.', characters: ['Tokio Jones', 'Morgan', 'Angela', 'Isaac Hayes'] },
    { title: 'Best Worst Night of My Life', summary: 'A performance by Willie Hutch causes Tokio to have a crisis of conscience about his chosen path.', characters: ['Tokio Jones', 'Willie Hutch'] },
    { title: 'Tube O’Caine', summary: 'A confrontation with another pimp leads to a strange encounter with Don "Magic" Juan\'s organization.', characters: ['Tokio Jones', 'Morgan', 'Angela', 'Patra'] },
    { title: 'Pimp or Be Pimped', summary: 'At the awards ceremony, Tokio wins "Best New-Jack," but his new girl, Patra, wins "Baddest Bitch," challenging his authority.', characters: ['Tokio Jones', 'Morgan', 'Angela', 'Patra', 'Dolomite'] },
    { title: 'Fuck Yo’ Chapter Titles', summary: 'Tokio reflects on the meta-narrative of his own story and his relationship with the author, Janice.', characters: ['Tokio Jones', 'Janice'] },
    { title: '#1 Stunner', summary: 'Patra reveals her true nature as a dominant and master manipulator, taking control of the stable and Tokio\'s life.', characters: ['Tokio Jones', 'Morgan', 'Angela', 'Patra'] },
    { title: 'Nightcap', summary: 'The first night with Patra culminates in a complex scene of discipline and pleasure, establishing the new hierarchy.', characters: ['Tokio Jones', 'Morgan', 'Angela', 'Patra'] },
    { title: 'Suite Mack', summary: 'The group moves to a luxury suite at the MGM Grand, beginning a week of opulence and Patra\'s re-education of Tokio in the high-end hustle.', characters: ['Tokio Jones', 'Morgan', 'Angela', 'Patra'] },
    { title: 'Superfly', summary: 'A night out to see Curtis Mayfield perform leads to Tokio acquiring two of the singer\'s backup singers, Jade and Mary, for his stable.', characters: ['Tokio Jones', 'Morgan', 'Angela', 'Patra', 'Jade', 'Mary', 'Curtis Mayfield'] },
    { title: 'Slumber Party', summary: 'The now-expanded group adjusts to their new dynamic, with Patra managing the household and the other girls.', characters: ['Tokio Jones', 'Morgan', 'Angela', 'Patra', 'Jade', 'Mary'] },
    { title: 'Entourage', summary: 'Tokio decides to take a high-paying construction job in Germany, and the entire entourage prepares for an international move.', characters: ['Tokio Jones', 'Morgan', 'Angela', 'Patra', 'Jade', 'Mary'] },
    { title: 'Willkommen in Deutschland', summary: 'The group arrives in Germany, where Patra\'s connections and business acumen quickly establish their new operation.', characters: ['Tokio Jones', 'Morgan', 'Angela', 'Patra', 'Jade', 'Mary'] },
];

export const radarLoveChapters: Chapter[] = [
    { title: 'Meet Chris and Janique', summary: 'Chris and Janique are introduced in separate prisons. Janique establishes dominance while Chris makes a calculated, violent move to establish his reputation.', characters: ['Chris Turner', 'Janique Turner'] },
    { title: 'The Robbery', summary: 'Flashback to the final pet store robbery that led to their arrest, where the owner is accidentally killed by Janique.', characters: ['Chris Turner', 'Janique Turner'] },
    { title: 'Ultimate Hustle', summary: 'Chris is mentored by Tokio Jones, a legendary pimp who introduces him to the concept of pornography as a more viable criminal enterprise than prostitution.', characters: ['Chris Turner', 'Tokio Jones'] },
    { title: 'The Wedding', summary: 'A flashback to Chris and Janique\'s symbolic wedding, involving a BDSM piercing ritual performed by Chris\'s ex-wife.', characters: ['Chris Turner', 'Janique Turner', 'Camilla'] },
    { title: 'They Meet', summary: 'A flashback detailing the first meeting of Chris and Janique at a Dairy Queen and the beginning of their intense romance.', characters: ['Chris Turner', 'Janique Turner'] },
    { title: 'Shaolin', summary: 'A flashback to Chris and Janique taking martial arts lessons together, deepening their bond and preparing them for a life of crime.', characters: ['Chris Turner', 'Janique Turner'] },
    { title: 'Slingshot', summary: 'In the present, Janique successfully sends a message to Chris in the prison yard. Chris, in turn, takes a hit for the Aryan Brotherhood to gain power and resources.', characters: ['Chris Turner', 'Janique Turner', 'Alvin Black', 'Martinez'] },
    { title: 'Circus Aflame', summary: 'Chris executes the hit on Omar Chapas by staging an overdose. Janique has an intense, surreal dream about her and Chris in a circus.', characters: ['Chris Turner', 'Janique Turner', 'Omar Chapas'] },
    { title: 'The Lion’s Share', summary: 'A flashback to a dangerous incident where a drug-fueled Janique wanders into a lion enclosure at the zoo.', characters: ['Chris Turner', 'Janique Turner'] },
    { title: 'Dirty Laundry', summary: 'Janique begins working in the prison laundry, realizing she can send secret messages to Chris through the uniforms. Her lawyers attempt to betray Chris, which she refuses.', characters: ['Janique Turner', 'Jeanette Gutierrez'] },
    { title: 'LY', summary: 'Janique embroiders "LY" (Love You) on the uniforms sent to the men\'s prison. She also gets her iconic sword tattoo.', characters: ['Janique Turner', 'Lexington / "Lexi"'] },
    { title: 'The Replica', summary: 'Janique fashions a replica of Chris\'s penis. She is nearly caught during a shakedown.', characters: ['Janique Turner', 'Jeanette Gutierrez'] },
    { title: 'Construction Begins', summary: 'Chris becomes a trustee and the foreman of a construction project that involves renovating the laundry, bringing him closer to Janique.', characters: ['Chris Turner', 'Earl Warren', 'Tokio Jones'] },
    { title: 'A Dream’s Foundation', summary: 'Chris and Janique have their first face-to-face encounter in months when he enters the laundry repair room.', characters: ['Chris Turner', 'Janique Turner', 'Jeanette Gutierrez'] },
    { title: 'Steady Hustling', summary: 'Chris and his crew begin building a secret "love nest" in a plumbing chase connected to the laundry. Janique has a sexual encounter with her prison "family".', characters: ['Chris Turner', 'Janique Turner', 'Mica', 'Jill'] },
    { title: 'Willie Wonka', summary: 'Chris deals with the murder of his bunkmate, Rolando. Jeanette, Rolando\'s aunt, is devastated, and Janique vows revenge, not knowing Chris is the killer.', characters: ['Chris Turner', 'Janique Turner', 'Jeanette Gutierrez', 'Rolando'] },
    { title: 'Another Body Murdered', summary: 'Chris is put in a difficult position when he is ordered to kill Tokio. In reality, it is a setup by Tokio to attempt an escape, which fails, leaving him paralyzed.', characters: ['Chris Turner', 'Tokio Jones'] },
    { title: 'Janique and the Hitman', summary: 'Unaware of the details, Janique puts out a hit on the person who killed Rolando, inadvertently targeting Chris.', characters: ['Janique Turner', 'Amy'] },
    { title: 'Lie Down With Dogs', summary: 'The prison warden attempts to extort sexual favors from Janique, using the hit she placed as leverage. She refuses and is sent to solitary.', characters: ['Janique Turner', 'Warden'] },
    { title: 'The Chase', summary: 'Chris and Janique are finally reunited in the secret room, where he reveals his escape plan involving a gas explosion.', characters: ['Chris Turner', 'Janique Turner'] },
    { title: 'The Love Nest', summary: 'Chris and Janique execute their escape plan during a chaotic trial where the charges against Janique are dismissed.', characters: ['Chris Turner', 'Janique Turner'] },
    { title: 'Absence Makes The Heart Grow Fonder', summary: 'A reflection on Janique\'s time in solitary and the growing tensions of the escape plan.', characters: ['Janique Turner'] },
    { title: 'No Deal', summary: 'Janique meets with her lawyers again and refuses their deal, solidifying her choice to stay with Chris.', characters: ['Janique Turner'] },
    { title: 'Under the Banyan Tree', summary: 'Chris finalizes the preparations for the escape, including the construction of a beautiful mural for Janique.', characters: ['Chris Turner', 'Pablo'] },
    { title: 'Memorial to Mr. Earl', summary: 'A dedication to the corrupt contractor who unknowingly funded the escape.', characters: ['Earl Warren'] },
    { title: 'The Lovers Reunited', summary: 'The final, explosive escape from prison.', characters: ['Chris Turner', 'Janique Turner'] },
    { title: 'The Princess & The Outlaw', summary: 'Now free, Chris and Janique retrieve their hidden money and start their new life on the run.', characters: ['Chris Turner', 'Janique Turner'] },
];

export const penultimateHustleJapanChapters: Chapter[] = [
    { title: 'Mommy Dearest', summary: 'Introduction to Janique as a powerful executive in the adult film industry in California.', characters: ['Janique Turner', 'Johnny Turner', 'Rai'] },
    { title: 'Life in the Fast Lane', summary: 'Chris works on pre-production for a film, highlighting the scale of their new operation.', characters: ['Chris Turner', 'Natalia', 'Yuki'] },
    { title: 'The Love Boat', summary: 'Flashback to Chris and Janique working on a cruise ship to escape the US after their prison break.', characters: ['Chris Turner', 'Janique Turner'] },
    { title: 'Osaka Harbor', summary: 'Flashback to their harrowing arrival in Japan and their first encounter with the Yakuza.', characters: ['Chris Turner', 'Janique Turner'] },
    { title: 'Hazel Minx', summary: 'Chris and Janique meet Hazel Minx, Tokio Jones\'s second-in-command, beginning a tense mentorship and rivalry.', characters: ['Chris Turner', 'Janique Turner', 'Hazel Minx'] },
    { title: 'Pimpin\' Ain\'t Easy', summary: 'Hazel outlines the current state of the business in Japan, and Chris and Janique are given their new roles.', characters: ['Chris Turner', 'Janique Turner', 'Hazel Minx'] },
    { title: 'The Game', summary: 'Janique challenges Hazel\'s business model, proposing a move into high-end film production.', characters: ['Janique Turner', 'Hazel Minx'] },
    { title: 'Production Value', summary: 'Janique begins pre-production for "Cherry Blossoms", hiring an effects artist and cinematographer.', characters: ['Chris Turner', 'Janique Turner'] },
    { title: 'Plain White Panties', summary: 'Chris writes a script based on poetry for Janique, who critiques and improves it.', characters: ['Chris Turner', 'Janique Turner'] },
    { title: 'Smell the Set-Up', summary: 'Janice, the US-based receptionist, conspires with Natalia to embezzle from the company.', characters: ['Janice', 'Natalia'] },
    { title: 'The Replica, Revisited', summary: 'Janique has a mold of Chris\'s penis cast for a special effects shot, leading to a scene with three Japanese makeup artists.', characters: ['Chris Turner', 'Janique Turner'] },
    { title: 'Slouching Toward Bethlehem', summary: 'Janice decides to seduce Brad, the lead engineer, to gain access to the database.', characters: ['Janice', 'Natalia'] },
    { title: 'Wardrobe and Script', summary: 'Janique shops for costumes, and Chris finalizes the script for "Cherry Blossoms" with her input.', characters: ['Chris Turner', 'Janique Turner'] },
    { title: 'Action', summary: 'Filming begins on "Cherry Blossoms".', characters: ['Chris Turner', 'Janique Turner'] },
    { title: 'Cherry Blossoms', summary: 'The film is a massive success, proving Janique\'s business model and increasing her power.', characters: ['Chris Turner', 'Janique Turner', 'Hazel Minx'] },
    { title: 'Pageburner', summary: 'Janique reads a trashy detective novel, which gives her the idea to investigate Hazel.', characters: ['Janique Turner'] },
    { title: 'Dinner is Served', summary: 'Janique, in disguise as an SEC agent, infiltrates the accounting firm and seduces an intern to gain access to financial records.', characters: ['Janique Turner', 'Yvette Kohan'] },
    { title: 'Hello Yuki', summary: 'Janique meets Yuki, a brilliant, precocious young fan, who quickly becomes her protégée.', characters: ['Janique Turner', 'Yuki'] },
    { title: 'Gangsta Shit', summary: 'Janique convinces a reluctant Hazel to fund the licensing for "Gojira\'s Revenge" by appealing to her "gangsta" roots.', characters: ['Janique Turner', 'Hazel Minx', 'Chris Turner'] },
    { title: 'Isle of Lucy', summary: 'Janique and Yuki meet for lunch at a bizarre, Lucille Ball-themed restaurant.', characters: ['Janique Turner', 'Yuki'] },
    { title: 'Pink Ninjas', summary: 'Janique and Yuki, dressed as ninjas, break into the studio of a reclusive CGI artist to recruit him for the film.', characters: ['Janique Turner', 'Yuki'] },
    { title: 'Labyrinth\'s Animator', summary: 'Janique and Yuki successfully recruit the artist, Yoichiro Kawaguchi, through a combination of business savvy and seduction.', characters: ['Janique Turner', 'Yuki', 'Yoichiro Kawaguchi'] },
    { title: 'Gojira\'s Revenge', summary: 'Chris finishes the script for the new film, which Janique approves without changes.', characters: ['Chris Turner', 'Janique Turner'] },
    { title: 'Masterpiece', summary: 'The film is described as a masterpiece of B-movie art, blending cheesy effects with a complex narrative.', characters: ['Chris Turner', 'Janique Turner', 'Yuki'] },
    { title: 'Janique the Green-Eyed Monster', summary: 'Janique struggles with jealousy over Chris\'s potential attraction to Yuki.', characters: ['Chris Turner', 'Janique Turner'] },
    { title: 'Training Session', summary: 'Janique and Yuki pick up the finished costumes. Janique "trains" Yuki by having her service Chris.', characters: ['Chris Turner', 'Janique Turner', 'Yuki'] },
    { title: 'Dusted', summary: 'Chris is accidentally dosed with PCP-laced weed by Hazel.', characters: ['Chris Turner', 'Hazel Minx'] },
    { title: 'Another Pet Shop of Horrors', summary: 'Under the influence of the PCP, Chris has a violent, surreal shootout with ninjas at a pet store.', characters: ['Chris Turner'] },
    { title: 'Roy G. Biv', summary: 'The ninjas Chris fights are revealed to be color-coded, like a rainbow.', characters: ['Chris Turner'] },
    { title: 'Easy Money', summary: 'Chris survives the shootout and wires the money he collected to Tokio\'s defense attorneys in the U.S.', characters: ['Chris Turner', 'Hazel Minx'] },
    { title: 'The Dress', summary: 'Chris returns to the apartment where Janique and Yuki are preparing for a ceremonial "wedding".', characters: ['Chris Turner', 'Janique Turner', 'Yuki'] },
    { title: 'The Ceremony', summary: 'The trio enacts a bizarre wedding ceremony, solidifying their three-way relationship.', characters: ['Chris Turner', 'Janique Turner', 'Yuki'] },
    { title: 'Special Delivery', summary: 'The Gojira and Ultrawoman costumes are delivered.', characters: ['Chris Turner', 'Janique Turner', 'Yuki'] },
    { title: 'Be Very Afraid', summary: 'Janique disciplines Yuki for her perceived transgressions.', characters: ['Janique Turner', 'Yuki'] },
    { title: 'Pet', summary: 'The power dynamic between the three is further explored through a scene of BDSM.', characters: ['Chris Turner', 'Janique Turner', 'Yuki'] },
    { title: 'Ultrawoman', summary: 'Janique reveals her completed, weaponized Ultrawoman costume.', characters: ['Janique Turner'] },
    { title: 'Willy Wonka Returns', summary: 'Yuki returns with snacks and a large bag of "Willy Wonka" weed, a strain Chris knows from prison.', characters: ['Chris Turner', 'Janique Turner', 'Yuki'] },
    { title: 'The Better to Eat You With', summary: 'The trio gets high and prepares to test the Gojira suit.', characters: ['Chris Turner', 'Janique Turner', 'Yuki'] },
    { title: 'The Dance', summary: 'Chris teaches Yuki how to waltz to coordinate their movements inside the Gojira suit.', characters: ['Chris Turner', 'Yuki'] },
    { title: 'Ultimate Demo', summary: 'The trio tests the suits\' functions, including a flamethrower and laser eyes.', characters: ['Chris Turner', 'Janique Turner', 'Yuki'] },
    { title: 'Battle Royale with Cheese', summary: 'The rehearsal turns into a full-blown, violent, and sexual battle between Gojira (Chris and Yuki) and Ultrawoman (Janique).', characters: ['Chris Turner', 'Janique Turner', 'Yuki'] },
    { title: 'Reptile Love', summary: 'The battle culminates in a three-way sexual encounter inside and with the costumes.', characters: ['Chris Turner', 'Janique Turner', 'Yuki'] },
    { title: 'Aftermath', summary: 'The trio recovers from their "rehearsal".', characters: ['Chris Turner', 'Janique Turner', 'Yuki'] },
    { title: 'Attacking the Streets of Tokyo', summary: 'The group scouts locations for the film and has a spontaneous sexual encounter on a subway train, which is filmed by Akira.', characters: ['Chris Turner', 'Janique Turner', 'Yuki', 'Akira'] },
    { title: 'Final Curtain', summary: 'The film is a massive success. With proof of her theft, Yuki murders Hazel, and the trio escapes Japan with Tokio\'s money.', characters: ['Chris Turner', 'Janique Turner', 'Yuki', 'Hazel Minx'] },
];

export const pageburnerChapters: Chapter[] = [
    { title: 'A Fishy Tale', summary: 'Detective Paige Burner solves the bizarre "lobster death" case of Maureen Bedford.', characters: ['Paige Burner', 'Clement Blankenship'] },
    { title: 'Just a Good Old Boy', summary: 'Introduction to Dr. Jean Simons, a brilliant but arrogant geneticist in Alabama.', characters: ['Dr. Jean Simons', 'James "Jimbrowski" Brown'] },
    { title: 'Square Peg', summary: 'Paige starts her new role as Head of Investigative Services, dealing with the aftermath of the lobster case.', characters: ['Paige Burner', 'Chief Terry', 'Philip K. "P.J." Johnson'] },
    { title: 'Fascist Gene', summary: 'Jean discusses his secret thesis on eradicating psychopathy via a targeted virus with his mentor, Dr. Woodard.', characters: ['Dr. Jean Simons', 'Dr. Woodard'] },
    { title: 'Square Peg, Part Two', summary: 'Paige and P.J. have a working lunch, where she mentors him on detective work.', characters: ['Paige Burner', 'P.J. Johnson'] },
    { title: 'Busted', summary: 'Jean has a close call with the police, which is defused by Maxine "Maxxy" Jackson, solidifying their relationship.', characters: ['Dr. Jean Simons', 'Maxine "Maxxy" Jackson'] },
    { title: 'Square Peg, Part Three', summary: 'Paige continues to settle into her new role, hiring the Chang twins and dealing with the department\'s bureaucracy.', characters: ['Paige Burner', 'John Chang', 'Lisa Chang'] },
    { title: 'The Trip', summary: 'Jean and Maxine take a psychedelic trip on LSD, a formative experience for their relationship and Jean\'s mission.', characters: ['Dr. Jean Simons', 'Maxine "Maxxy" Jackson'] },
    { title: 'R & R', summary: 'Paige takes a much-needed vacation to New Orleans, where she has a brief, intense affair.', characters: ['Paige Burner'] },
    { title: 'Departure', summary: 'Jean graduates and leaves Alabama for California to start his career, leaving a pregnant Maxine behind, though he is unaware of the pregnancy.', characters: ['Dr. Jean Simons', 'Maxine "Maxxy" Jackson', 'Pookie'] },
    { title: 'R & R Part Two', summary: 'Paige continues her road trip through Tennessee, revisiting childhood memories.', characters: ['Paige Burner'] },
    { title: 'Departure, Part Two', summary: 'Maxine deals with Jean\'s departure and the discovery of her pregnancy.', characters: ['Maxine "Maxxy" Jackson'] },
    { title: 'Paige A Go-Go', summary: 'Paige returns to California, feeling restless, and throws herself back into her work and personal routines.', characters: ['Paige Burner'] },
    { title: 'Road Scholar', summary: 'Jean travels across the country to California, settling into his new job at D-Generation.', characters: ['Jean Simons'] },
    { title: 'Arrested Development', summary: 'Paige, now Head of Investigative Services, deals with a new murder case involving stolen art and Che Guevara memorabilia.', characters: ['Paige Burner', 'P.J. Johnson'] },
    { title: 'California, Ho!', summary: 'Jean establishes his new life in California, including making contact with Maxine\'s "Uncle Pook" for supplies.', characters: ['Jean Simons', 'Pookie'] },
    { title: 'Rock for Light', summary: 'Paige solves the art theft murder, further solidifying her reputation.', characters: ['Paige Burner', 'P.J. Johnson', 'Chief Terry'] },
    { title: 'Revelation', summary: 'Jean has a profound, mystical experience on Ayahuasca, which confirms his mission as "The Messiah".', characters: ['Jean Simons'] },
    { title: 'Rock City', summary: 'Paige continues her solitary vacation, visiting Rock City in Tennessee.', characters: ['Paige Burner'] },
    { title: 'Revelation, Part Two', summary: 'Jean\'s ayahuasca trip continues, showing him the nature of reality and the genetic code he needs for his virus.', characters: ['Jean Simons'] },
    { title: 'Sleeping Village', summary: 'Paige finishes her vacation, feeling a mix of melancholy and resolve to change her life.', characters: ['Paige Burner'] },
    { title: 'Messiah', summary: 'Jean, now fully embracing his messianic role, begins the practical work of creating his virus.', characters: ['Jean Simons'] },
    { title: 'Childhood\'s End', summary: 'Paige returns to work and her promotion, ready to reshape the department.', characters: ['Paige Burner', 'Chief Terry'] },
    { title: 'Fate, Tempted', summary: 'A chance encounter at a chemical supply house brings Jean and Paige together for the first time.', characters: ['Jean Simons', 'Paige Burner'] },
    { title: 'The Triumphant Return', summary: 'Paige fully takes charge of her new department, hiring P.J. and the Chang twins.', characters: ['Paige Burner', 'P.J. Johnson', 'John Chang', 'Lisa Chang'] },
    { title: 'Ouroboros Rising', summary: 'Jean successfully tests his first virus on a genetic sample of Charles Manson, who dies in prison days later.', characters: ['Jean Simons'] },
    { title: 'Shake It Up', summary: 'Paige settles into her new role, clashing with and then winning over the chief.', characters: ['Paige Burner', 'Chief Terry'] },
    { title: 'So It Begins', summary: 'Jean prepares and mails his manifesto to the media, declaring the coming of "Captain Trips".', characters: ['Jean Simons'] },
    { title: 'Unintended Consequences', summary: 'Paige\'s new department structure and software begin to show positive results.', characters: ['Paige Burner', 'John Chang', 'Lisa Chang', 'Chief Terry'] },
    { title: 'Onward and Upward', summary: 'Jean travels to Colorado to release the second, limited version of his virus.', characters: ['Jean Simons'] },
    { title: 'Confirmation', summary: 'Paige connects the Colorado deaths to her other cases, realizing a serial killer using a bioweapon is at work.', characters: ['Paige Burner', 'David Rogers'] },
    { title: 'Dinner at Pepper\'s', summary: 'Paige meets with Jean under the guise of an interview, confirming her suspicions that he is the killer.', characters: ['Paige Burner', 'Jean Simons'] },
    { title: 'Cold Virus', summary: 'Jean successfully releases the virus at the Deer Valley ski resort, causing five deaths among the wealthy vacationers.', characters: ['Jean Simons'] },
    { title: 'The Reporter', summary: 'Paige, posing as a reporter, calls Maxine to gather more information on Jean, inadvertently learning Maxine is pregnant.', characters: ['Paige Burner', 'Maxine "Maxxy" Jackson'] },
    { title: 'Tenderness', summary: 'Paige flies to Alabama and meets Maxine. Their initial mistrust blossoms into a physical and emotional intimacy.', characters: ['Paige Burner', 'Maxine "Maxxy" Jackson'] },
    { title: 'Collusion', summary: 'Paige and Maxine team up, visiting Dr. Woodard and Jimbrowski to confirm Jean\'s movements and lies.', characters: ['Paige Burner', 'Maxine "Maxxy" Jackson', 'Dr. Woodard', 'James "Jimbrowski" Brown'] },
    { title: 'Showdown', summary: 'Paige confronts Jean at a motel in East L.A. as he prepares to release the final virus. He is shot by Uncle Pookie.', characters: ['Paige Burner', 'Jean Simons', 'Pookie'] },
    { title: 'Happy Unending', summary: 'Paige releases the final virus herself. Jean survives and is reunited with Maxine and their newborn son. The three face an uncertain future together.', characters: ['Paige Burner', 'Jean Simons', 'Maxine "Maxxy" Jackson'] },
];

export const hurricaneReginaChapters: Chapter[] = [
    { title: 'Overboard', summary: 'Captain Dan Nolan\'s vessel is the site of Regina Long\'s disappearance as she falls overboard.', characters: ['Captain Dan Nolan', 'Regina Long'] },
    { title: 'National Insecurity', summary: 'President Long is alerted to his daughter\'s kidnapping and the national security crisis it represents.', characters: ['President Robert "Lazarus" Long'] },
    { title: 'Paperclips and Butterflies', summary: 'The kidnapper, "Tom," reveals his knowledge of secret government mind-control programs to Regina.', characters: ['Regina Long', '"Tom"'] },
    { title: 'First Impressions', summary: 'Regina calls her father with Tom\'s demands. Captain Dan recalls his first, confrontational meeting with Regina on his ship.', characters: ['Regina Long', 'President Long', 'Captain Dan Nolan'] },
    { title: 'Yum', summary: 'Dan remembers making breakfast for Regina and their conversation about her running away.', characters: ['Regina Long', 'Captain Dan Nolan'] },
    { title: 'Meet Albert Einstein', summary: 'President Long and his advisor, Albert "Al" Onestone, arrive to brief Dan, providing him with advanced tracking technology.', characters: ['President Long', 'Albert "Al" Onestone', 'Captain Dan Nolan'] },
    { title: 'Lord Petrus T. Steele', summary: 'An elderly patriot, Petrus Steele, activates his network of saboteurs in response to the President\'s speech.', characters: ['Lord Petrus T. Steele'] },
    { title: 'Revolution', summary: 'Patriot cells across the country begin to sabotage critical infrastructure, throwing the nation into chaos.', characters: ['Ferret'] },
    { title: 'Global Search', summary: 'Dan tracks Regina\'s signal to a point deep in the ocean, realizing the kidnappers are in a submarine.', characters: ['Captain Dan Nolan'] },
    { title: 'Uncivil War', summary: 'The country descends into chaos as a result of the sabotage. Dan prepares for a deep-sea rescue.', characters: ['Captain Dan Nolan'] },
    { title: 'Rescue?', summary: 'Regina discovers the true nature of Tom\'s underwater dome, "Eden," complete with a unicorn.', characters: ['Regina Long', '"Tom"'] },
    { title: 'Fantasy Gone Wrong', summary: 'Dan\'s rescue attempt turns into a disaster as Tom unleashes a dragon. Regina discovers her own latent powers.', characters: ['Captain Dan Nolan', 'Regina Long', '"Tom"'] },
    { title: 'Betrayed', summary: 'Regina defeats Tom, only to discover he is a clone and the real Tom is an incorporeal entity. She seemingly kills him and escapes with Dan.', characters: ['Regina Long', 'Captain Dan Nolan', '"Tom"'] },
    { title: 'Hurricane Regina', summary: 'Regina\'s powers cause massive geological upheaval across the planet. She remakes a part of the world into her new "Eden".', characters: ['Regina Long'] },
    { title: 'Dome', summary: 'The President and Al are trapped on an invisible platform near the new island, surrounded by prehistoric sea creatures.', characters: ['President Long', 'Albert "Al" Onestone'] },
    { title: 'The Proposal', summary: 'Dan confronts Regina on her island, who reveals her plan to remake the world and that she is now pregnant with his child via her powers.', characters: ['Regina Long', 'Captain Dan Nolan'] },
    { title: 'In an Icelandic McDonald\'s', summary: 'Dan, the President, and Al find a cryptic clue in a newspaper that leads them to Oak Island.', characters: ['Captain Dan Nolan', 'President Long', 'Albert "Al" Onestone'] },
    { title: 'Goddesshead', summary: 'Regina\'s power grows as she begins sorting humanity, but she is stalled by self-doubt and the unexpected rapid growth of her unborn child, Tommy.', characters: ['Regina Long', 'Tommy'] },
    { title: 'The Money Pit', summary: 'The group begins an excavation on Oak Island, led by Renee Hollander, which proves to be a trap.', characters: ['Captain Dan Nolan', 'President Long', 'Albert "Al" Onestone', 'Renee Hollander'] },
];

export const zombieKillaChapters: Chapter[] = [
    { title: 'The Odd Couple', summary: 'Introduction to Myf and his chaotic roommate, High-C.', characters: ['Myf', 'High-C'] },
    { title: 'Karyn Crisis In The Kremlin', summary: 'The wider nerdcore hip-hop community is introduced, including YTCracker and MC Router.', characters: ['YTCracker', 'MC Router', 'Magitek'] },
    { title: 'Fear & Loathing In Cleveland', summary: 'High-C murders a police officer he believes to be a zombie, forcing him and Myf to go on the run to Florida.', characters: ['Myf', 'High-C'] },
    { title: 'All My Texts Originate in Texas', summary: 'The zombie plague, originating from MC Router in Dallas, begins to spread. Zealous1 mobilizes a force to fight it.', characters: ['MC Router', 'Zealous1'] },
    { title: 'Florida Sucks', summary: 'The trio (now including Nursehella) encounters more zombies on their way to Orlando.', characters: ['Myf', 'High-C', 'Nursehella'] },
    { title: 'Z.E.D.\'s Not Dead', summary: 'The nerdcore community gathers in Orlando, forming "Zombie Eradication Defense" (Z.E.D.).', characters: ['All Nerdcore MCs'] },
    { title: 'Federal Case, Jr.', summary: 'YTCracker negotiates immunity with the federal government for the nerdcore crew.', characters: ['YTCracker'] },
    { title: 'Louisiana Sucks, But Not As Much As Florida', summary: 'The convoy heads to Dallas, tricking the Louisiana State Troopers into giving them an escort.', characters: ['High-C', 'Nursehella'] },
    { title: 'Bad Mother Truckers', summary: 'The convoy is attacked by zombies in a semi-truck. Karl (Ultraklystron) is wounded.', characters: ['All Nerdcore MCs'] },
    { title: 'Hack Attack', summary: 'The teams begin their assault on Router\'s apartment complex. Team Hacker secures the first building.', characters: ['Team Hacker'] },
    { title: 'Balloonacy', summary: 'Team Psycho makes a chaotic entrance, crashing their jeep into a wall.', characters: ['Team Psycho'] },
    { title: 'Operation Europe', summary: 'The various teams converge on the apartment complex courtyard, facing heavy resistance.', characters: ['All Teams'] },
    { title: 'Locked Down', summary: 'Router creates a force field around her apartment. High-C goes on a solo mission to rescue Monny Veeps.', characters: ['Myf', 'High-C', 'Monny Veeps'] },
    { title: 'Peach Is the Word', summary: 'The teams destroy Router\'s force field with an enchanted bomb provided by Captain Dan.', characters: ['Betty Rebel', 'Captain Dan'] },
    { title: 'Victorious Secret', summary: 'High-C confronts and seemingly kills Router, ending the plague. The healers revive her.', characters: ['High-C', 'MC Router', 'YTCracker', 'Zealous1'] },
];

export const perfectMeChapters: Chapter[] = [
    { title: 'Prail', summary: 'Prail Abraxis is introduced as a brilliant game designer on Praxis, working on the Earth2 simulation.', characters: ['Prail Abraxis'] },
    { title: 'President Gorlax', summary: 'The hyper-violent President Gorlax of Gortician is introduced, along with his desire for Prail.', characters: ['President Gorlax'] },
    { title: 'Vnew Vreal', summary: 'Gorlax\'s beleaguered press secretary deals with the fallout of his boss\'s chaotic actions.', characters: ['Vnew Vreal'] },
    { title: 'Reaper Madness', summary: 'Prail works on her video game "Reaper Madness", a simulation of soul harvesting.', characters: ['Prail Abraxis'] },
    { title: 'The Mad Poet', summary: 'Sherman Oakes, the "mad poet", is commissioned by Gorlax to write love poems for Prail.', characters: ['Sherman Oakes', 'President Gorlax'] },
    { title: 'MotherBrain', summary: 'The ruler of Praxis, MotherBrain, senses the potential union of Gorlax and Prail and begins scheming.', characters: ['MotherBrain'] },
    { title: 'Classic Gaming', summary: 'Prail relaxes by updating classic video games into 3D versions.', characters: ['Prail Abraxis'] },
    { title: 'Vacation', summary: 'Sherman Oakes takes a vacation on Earth2 (Maui) to detox and relax.', characters: ['Sherman Oakes'] },
    { title: 'Construction Master', summary: 'Prail solves a major programming problem with the simulation\'s suns and works on her game "Construction Master".', characters: ['Prail Abraxis'] },
    { title: 'O.D. DrugWar', summary: 'Sherman Oakes contacts intergalactic drug dealers High-C and O.D. DrugWar to re-tox.', characters: ['Sherman Oakes', 'O.D. DrugWar'] },
    { title: 'Star Hustle', summary: 'A high Sherman Oakes calls the famous "Feelie" star Parabola Blue for a rendezvous.', characters: ['Sherman Oakes', 'Parabola Blue'] },
    { title: 'Judas Mason', summary: 'Arch-villainess Judas Mason learns of Sherman\'s pleasure and begins plotting his destruction.', characters: ['Judas Mason', 'President Gorlax'] },
    { title: 'Death Race 2000', summary: 'Prail works on her game "Death Race 2000", which leads to a breakthrough on her "writer sim" project.', characters: ['Prail Abraxis'] },
    { title: 'Earth’s Dead Serial Killers', summary: 'President Gorlax uses a "Necronomiphone" to consult Earth\'s dead serial killers for new torture methods.', characters: ['President Gorlax'] },
    { title: 'Survival of the Fittest', summary: 'Prail designs her animal combat game "Survival of the Fittest".', characters: ['Prail Abraxis'] },
    { title: 'AngVenn', summary: 'Vnew Vreal\'s nonsensical press release about Gorlax\'s trip attracts the romantic interest of journalist AngVenn.', characters: ['Vnew Vreal', 'AngVenn'] },
    { title: 'Barbarians', summary: 'Prail works on her historical combat game "Barbarians" as she awaits Gorlax\'s arrival.', characters: ['Prail Abraxis'] },
    { title: 'Reunited', summary: 'President Gorlax arrives on Praxis and meets Prail, who is charmed by his awkward attempts at romance.', characters: ['President Gorlax', 'Prail Abraxis', 'MotherBrain'] },
    { title: 'Oracle Jones', summary: 'Judas Mason consults her wise friend Oracle Jones on how best to destroy Sherman Oakes.', characters: ['Judas Mason', 'Oracle Jones'] },
    { title: 'Tessa Rack', summary: 'The trio of villainesses dines and plots.', characters: ['Judas Mason', 'Oracle Jones', 'Tessa Rack'] },
    { title: 'Perfections', summary: 'Prail gives Gorlax a tour of the "Perfection" labs, which ends with him being accidentally teleported to an Earth2 emergency room.', characters: ['Prail Abraxis', 'President Gorlax'] },
    { title: 'Healthcare', summary: 'Gorlax\'s violent nature leads to his incarceration on Earth2.', characters: ['President Gorlax'] },
    { title: 'Big Top', summary: 'Prail designs the circus management sim "Big Top".', characters: ['Prail Abraxis'] },
    { title: 'High-C', summary: 'High-C is introduced, cooking up new drugs in his lab.', characters: ['High-C', 'O.D. DrugWar'] },
    { title: 'President Gorlax Retreats', summary: 'Prail rescues Gorlax. Now back on his ship, he acquires a powerful new drug, "Sloe Deth," from High-C.', characters: ['President Gorlax', 'High-C'] },
    { title: 'Date Night', summary: 'Vnew Vreal and AngVenn go on their first date. Sherman Oakes prepares for his own date with Judas, Oracle, and Tess.', characters: ['Vnew Vreal', 'AngVenn', 'Sherman Oakes'] },
    { title: 'Party Time', summary: 'Sherman\'s orgy is a drug-fueled failure. Vnew and AngVenn get engaged.', characters: ['Sherman Oakes', 'Judas Mason', 'Oracle Jones', 'Tessa Rack', 'Vnew Vreal', 'AngVenn'] },
    { title: 'Bauhaus', summary: 'Prail works on her "writer sim" project.', characters: ['Prail Abraxis'] },
    { title: 'Black Vein Prophecy', summary: 'L\'viv has a terrible premonition about her sons.', characters: ['L\'viv'] },
    { title: 'Surprise!', summary: 'Judas reveals she has planted a bomb on Sherman\'s ship.', characters: ['Judas Mason', 'Oracle Jones', 'Tessa Rack'] },
    { title: 'Disaster Area', summary: 'The bomb explodes, sending Sherman and Death crash-landing on Faggotron.', characters: ['Sherman Oakes', 'Death'] },
    { title: 'Happy Ending?', summary: 'All the main characters converge on Faggotron. Sherman is healed, L\'viv is reunited with her sons, and three couples are married.', characters: ['All'] },
];

export const cureForSanityChapters: Chapter[] = [
    { title: 'Earthbound', summary: 'Pex, a higher-dimensional being, arrives on Earth in 1970s London to begin a "game" against his sister, Prail.', characters: ['Pex'] },
    { title: 'Steve from Tampa', summary: 'Pex, posing as a human, begins building a device to map the world, tricking Prail into processing the data.', characters: ['Pex', 'Prail', 'Janique'] },
    { title: 'Troubling Paradise', summary: 'Pex continues his work, while Prail begins to realize the complexity of his interference.', characters: ['Pex', 'Prail'] },
    { title: 'Like a Boss', summary: 'Pex infiltrates Prail\'s "McDonald\'s" simulation to taunt her. Janique confronts God about her creation.', characters: ['Pex', 'Prail', 'Janique', 'God'] },
    { title: 'Murder Most Foul', summary: 'Frustrated by her inability to harm her creators, Janique continues her attempts to kill Jason Christie across timelines, unaware she is only making him stronger.', characters: ['Janique', 'Prail', 'Pex'] },
    { title: 'Swamped Things', summary: 'Janique makes another attempt to kill Jason and Johnnie in a swamp, which Pex thwarts.', characters: ['Janique', 'Prail', 'Pex'] },
    { title: 'The Beet Farmer', summary: 'Pex travels back in time to recruit Yeshua (Jesus) as a pawn in his game.', characters: ['Pex', 'Yeshua'] },
    { title: 'The Alchemist', summary: 'Janique consults High-C to create a new drug, "Superlove," to use against her creators, discovering it is based on her own DNA.', characters: ['Janique', 'High-C'] },
    { title: 'Songs that Make the Young Girls Cry', summary: 'Pex laments how Jason Christie\'s embrace of Objectivism misses the point of the sci-fi subplot he embedded in "Atlas Shrugged".', characters: ['Pex', 'Jason Christie'] },
    { title: 'Welcome to Gortician', summary: 'Janique travels to Gortician to acquire advanced weaponry from President Gorlax.', characters: ['Janique', 'President Gorlax'] },
    { title: 'Foundation', summary: 'Pex lays the groundwork for the Knights Templar with Yeshua and Mary.', characters: ['Pex', 'Yeshua', 'Mary'] },
    { title: 'Knoxy', summary: 'Janique continues her research into Stephen King\'s novels, discovering their meta-connection to her reality and her creators.', characters: ['Janique', 'Prail'] },
    { title: 'Logic Bombs', summary: 'Prail and Janique discuss the nature of their reality, the sim, and the power of language.', characters: ['Prail', 'Janique'] },
    { title: 'Dark Hustle', summary: 'Pex and God discuss the nature of their power. Janique begins creating her own universes for "Dark Hustle".', characters: ['Pex', 'God', 'Janique'] },
    { title: 'Wise as Serpents', summary: 'Pex and God continue their discussion. Pex sends Yeshua and Mary to 1984 Las Vegas, hiding them inside Jason Christie.', characters: ['Pex', 'God', 'Yeshua', 'Mary'] },
    { title: 'Non-Prophets', summary: 'Janique, feeling maternal after a failed attempt to kidnap the baby Jesus, decides to abandon her quest for revenge.', characters: ['Janique', 'Pex'] },
    { title: 'The Passion of Mel Gibson', summary: 'Pex and Janique film a parody of "The Passion of the Christ" with Mel Gibson, which serves as a final lesson and resolution.', characters: ['Pex', 'Janique', 'Mel Gibson'] },
];
